# Generated by Django 3.2.6 on 2021-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile/', verbose_name='Ваша фотография')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты')),
                ('date_of_birth', models.DateField(max_length=10, verbose_name='Дата рождения')),
                ('country', models.CharField(max_length=25, verbose_name='Страна проживания')),
                ('city', models.CharField(max_length=25, verbose_name='Город проживания')),
            ],
        ),
    ]
