# Generated by Django 3.2.6 on 2021-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Название Вкансии')),
                ('location_where_work', models.CharField(max_length=30, null=True, verbose_name='Город/Страна где работать')),
                ('job_description', models.TextField(blank=True, verbose_name='Описание вакансии')),
                ('candidate_requirement', models.TextField(blank=True, verbose_name='Какой кандидат нам подходит')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации вакансии')),
                ('other_information_vacancy', models.TextField(blank=True, verbose_name='Соц пакет')),
            ],
        ),
    ]
