# Generated by Django 3.2.6 on 2021-09-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='Название компании')),
                ('company_icon', models.ImageField(blank=True, upload_to='images/company/logo/', verbose_name='Логотип компании')),
                ('company_description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('company_address_ofice', models.CharField(max_length=225, verbose_name='Адрес компании')),
                ('company_phone_number_1', models.CharField(max_length=20, verbose_name='Контактный телефон 1')),
                ('company_phone_number_2', models.CharField(max_length=20, verbose_name='Контактный телефон 2')),
            ],
        ),
    ]
